AllCops:
  NewCops: disable

Naming/MethodParameterName:
  MinNameLength: 1

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20
